require 'rubygems'
require 'rake/gempackagetask'
require 'rubygems/specification'
require 'date'
require 'erb'
require 'fileutils'

ROOT = File.expand_path(File.dirname(__FILE__))
require "#{ROOT}/lib/appengine-jruby-jars"

GEM_VERSION = AppEngine::JRubyJars::VERSION
JRUBY_VERSION = AppEngine::JRubyJars::JRUBY_VERSION

RBFILE = "lib/appengine-jruby-jars.rb"
ABRIDGED_JAR = "lib/appengine-jruby-#{GEM_VERSION}.jar"
JRUBY_COMPLETE = "jruby-complete-#{JRUBY_VERSION}.jar"
RUBYGEMS_JAR = "lib/appengine-jruby-rubygems-#{GEM_VERSION}.jar"
APPENGINE_BOOT = File.join(ROOT, 'appengine_boot.rb')
APPENGINE_COMMANDS = File.join(ROOT, 'appengine_commands.rb')

spec = Gem::Specification.new do |s|
  s.name = "appengine-jruby-jars"
  s.version = GEM_VERSION
  s.author = "Ryan Brown"
  s.email = "ribrdb@google.com"
  s.homepage = "http://code.google.com/p/appengine-jruby"
  s.description = s.summary = "JRuby jar files for Google App Engine."
  
  s.platform = Gem::Platform::RUBY
  
  # Uncomment this to add a dependency
  # s.add_dependency "foo"
  
  s.require_path = 'lib'
  s.files = Dir.glob("{LICENSE,COPYING}*") + [
      RBFILE, ABRIDGED_JAR, RUBYGEMS_JAR]
  s.add_development_dependency('appengine-rack', '1.0.0')
end

directory 'lib'

def check_system(*args)
  puts args.join(" ")
  unless system(*args)
    puts "Error running #{args[0].inspect}"
    exit($?)
  end
end

file ABRIDGED_JAR => [JRUBY_COMPLETE, 'Rakefile',
                      APPENGINE_BOOT, APPENGINE_COMMANDS] do
  require 'appengine-rack'
  verbose(true) do
    chdir(File.dirname(__FILE__)) do
      rm_rf('tmp')
      mkdir('tmp')
      chdir('tmp') do
        site_ruby = 'META-INF/jruby.home/lib/ruby/site_ruby/1.8/'
        check_system("jar", "xf", File.join(ROOT, JRUBY_COMPLETE))
        chdir(site_ruby) do
          gems_files = Dir.glob("rubygems*")
          check_system('jar', 'cf', File.join(ROOT, RUBYGEMS_JAR), *gems_files)
          rm_rf(gems_files)
        end
        rm_rf("META-INF/jruby.home/lib/ruby/gems")
        rm_rf("org/jruby/ext/ffi/jna")
        # prune the limited openssl warning
        if JRUBY_VERSION.eql?('1.3.1')
          nice_file = '__fixed__'
          warn_file = "#{site_ruby}jruby/openssl/builtin.rb"
          all_lines = IO.readlines(warn_file)
          open(nice_file, 'w') do |file|
            file.puts(all_lines[0..-5] + all_lines[-2..-1])
          end
          mv(nice_file, warn_file)
        end
        # redistribute some other files
        cp(File.join(AppEngine::Rack::ROOT, 'appengine-rack.rb'), site_ruby)
        cp_r(File.join(AppEngine::Rack::ROOT, 'appengine-rack'),
             File.join(site_ruby, 'appengine-rack'))
        Gem.activate(Gem::Dependency.new('rack', '1.0.0'))
        rack = Gem.loaded_specs['rack']
        rack_lib = File.join(rack.full_gem_path, 'lib')
        cp(File.join(rack_lib, 'rack.rb'), site_ruby)
        cp_r(File.join(rack_lib, 'rack'), File.join(site_ruby, 'rack'))
        cp(APPENGINE_BOOT, site_ruby)
        cp(APPENGINE_COMMANDS, File.join('jruby', 'commands.rb'))
        check_system("jar", "cf", File.join(ROOT, ABRIDGED_JAR), '.')
      end
      rm_rf('tmp')
    end
  end
end

task :default => :gem

Rake::GemPackageTask.new(spec).define

desc "install the gem locally"
task :install => [:package] do
  sh %{sudo gem install pkg/#{GEM}-#{GEM_VERSION}}
end

desc "create a gemspec file"
task :make_spec do
  open("#{GEM}.gemspec", "w") do |file|
    file.puts spec.to_ruby
  end
end
